# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

!pip install pyspark

from pyspark.sql import SparkSession

# Spark session start
spark = SparkSession.builder.appName("SimpleLocalPipeline").getOrCreate()

# Dummy Data
data = [
    (1, "Aman", "Laptop", 50000),
    (2, "Rahul", "Phone", 20000),
    (3, "Priya", "Tablet", 15000),
    (4, "Aman", "Headphones", 2000)
]

columns = ["order_id", "customer_name", "product", "amount"]

# DataFrame
df = spark.createDataFrame(data, schema=columns)

print("--- Original Data ---")
df.show()

# Filter Data (Amount > 10000)
filtered_df = df.filter(df["amount"] > 10000)

print("--- Filtered Data (Amount > 10000) ---")
filtered_df.show()

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, when, current_timestamp, avg, count

# 1. Spark Session
spark = SparkSession.builder.appName("CloudDataPipelineProject").getOrCreate()

# 2. Mock Dataset 1: Sales Transactions (Relational Data)
sales_data = [
    (101, 1001, "Laptop", "Electronics", 75000.0, "2026-03-01"),
    (102, 1002, "Phone", "Electronics", 25000.0, "2026-03-01"),
    (103, 1001, "Headphones", "Accessories", 2000.0, "2026-03-02"),
    (104, 1003, "Monitor", "Electronics", 15000.0, "2026-03-02"),
    (105, 1004, "Chair", "Furniture", 8000.0, "2026-03-03"),
    (106, 1002, "Mouse", "Accessories", 1200.0, "2026-03-03")
]
sales_cols = ["order_id", "user_id", "product_name", "category", "price", "order_date"]
sales_df = spark.createDataFrame(sales_data, schema=sales_cols)

# 3. Mock Dataset 2: User Activity Logs (NoSQL Data)
user_logs = [
    (1001, "Chrome", "India", "Completed"),
    (1002, "Firefox", "India", "Completed"),
    (1003, "Safari", "USA", "Pending"),
    (1004, "Chrome", "UK", "Completed"),
    (1005, "Chrome", "India", "Failed")
]
logs_cols = ["user_id", "browser", "country", "payment_status"]
logs_df = spark.createDataFrame(user_logs, schema=logs_cols)

print("--- Sales Data ---")
sales_df.show()

print("--- User Activity Logs ---")
logs_df.show()

# 1. Data Cleaning: Only successful payment transactions
valid_logs = logs_df.filter(col("payment_status") == "Completed")

# 2. Join Both Datasets on user_id
pipeline_df = sales_df.join(valid_logs, on="user_id", how="inner")

# 3. Feature Engineering: Timestamp & High-Value Flag add karna
final_df = pipeline_df.withColumn("ingested_at", current_timestamp()) \
                      .withColumn("is_high_value", when(col("price") >= 20000, "YES").otherwise("NO"))

print("--- Transformed Pipeline Output ---")
final_df.show()

# 4. Business Metrics Aggregation (Country-wise Sales)
metrics_df = final_df.groupBy("country") \
                     .agg(count("order_id").alias("total_orders"),
                          avg("price").alias("avg_order_value"))

print("--- Business Insights (Aggregations) ---")
metrics_df.show()

# Save Processed Data to Parquet (Storage step)
final_df.write.mode("overwrite").parquet("processed_sales_parquet")

print("Pipeline executed successfully! Parquet files created.")

pip install apache-airflow

!pip install "opentelemetry-api<=1.42.1" "opentelemetry-sdk<=1.42.1"

!pip install "opentelemetry-api<=1.44.0" "opentelemetry-sdk<=1.44.0"

import os
from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator

def run_pyspark_job():
    print("PySpark Job Triggered Successfully via Airflow Task!")

default_args = {
    'owner': 'data_engineering_team',
    'start_date': datetime(2026, 1, 1),
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

# 'schedule_interval' ki jagah 'schedule' use karein
dag = DAG(
    'cloud_data_pipeline_dag',
    default_args=default_args,
    schedule='@daily',  # <--- UPDATED HERE
    catchup=False
)

task1 = PythonOperator(
    task_id='run_pyspark_transformation',
    python_callable=run_pyspark_job,
    dag=dag
)

print("--- Testing Airflow DAG Execution ---")
task1.execute(context={})

